saiyagym:
  property: Prueba Profile Dev

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/prueba
    username: postgres
    password: postgres 